Petit éclaircissement sur la configuration à employer avec AirTable
DISIC/design.numerique.gouv.fr pull request #264
Opened 2022-02-19 14:32 UTC by Stef-33560

Couplage fort à airtable.com, ça mériterait d'être précisé

2023-06-12 08:39 UTC, alanlecart approved these changes
Oui bon à préciser, sinon impossible de démarrer le projet

2023-06-12 08:55 UTC, alanlecart commented
D'ailleur les API Keys seront dépréciées dans un futur proche 
![image](https://github.com/DISIC/design.numerique.gouv.fr/assets/35492348/75e9ca85-e66e-4106-afd3-8cb7f6620300)

2024-02-27 23:38 UTC, thomasbnt requested changes

2024-02-27 23:38 UTC, thomasbnt commented on README.md
> +  - GRIDSOME_AIRTABLE_API_KEY: clé d'API Airtable pouvant être trouvé une fois loggué dans airtable.com, sous "ACCOUNT > API"
```suggestion
  - GRIDSOME_AIRTABLE_KEY: clé d'API Airtable pouvant être trouvé une fois loggué dans airtable.com, sous "ACCOUNT > API"
```

Modification du nom de la variable depuis https://github.com/DISIC/design.numerique.gouv.fr/commit/e722ca342d2529da5c0a0f3444a78caae178da25

2025-02-20 12:39 UTC, ClementNumericite commented
Suite à l'implémentation de Grist en remplacement d'Airtable, je ferme cette PR.

Le README a été mis à jour avec tous les éléments nécessaires.

2025-02-20 12:39 UTC, closed without merging